# Title of your site
title: testing testing testing

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl: '/'

# Name the theme folder in `themes/`.
theme: hugo-testing
languageCode: en-us

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: pygments

menu:
  main:
  - name: Home
    url: /
    weight: 1
  - name: Blog
    url: /blog/
    weight: 2
