# Title of your site
title: Tidyverse

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl: 'https://www.tidyverse.org/'

# Name the theme folder in `themes/`.
theme: hugo-tourmaline
# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics: UA-115082821-1

relativeurls: false
languageCode: en-us
description: An opinionated collection of R packages designed for data science.
disqusShortname: ''
ignoreFiles: ['\.Rmd$', '_files$', '_cache$', 'articles/.*']
# below is critical for non-authors to show up in article listing
preserveTaxonomyNames: true

permalinks:
  blog: 'blog/:year/:month/:slug/'
  articles: 'articles/:year/:month/:slug/'

taxonomies:
  category: categories
  tag: tags

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: pygments

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: true
  twitter:
    enableDNT: true
    privacyEnhanced: true

menu:
  main:
  - name: Blog
    url: /blog/
    weight: 1

params:
  description: >-
    The tidyverse is an integrated collection of R packages designed to make data
    science fast, fluid, and fun.
  copy_clipboard: true
  sharing_image: tidyverse-default.png
  twitter_image: hex-tidyverse.png
  custom_css:
    - ''
  hex_base_url: .tidyverse.org
  mainSections:
    - articles
    - events
  disable_highlightjs: 'true'
  highlightjsVersion: 9.11.0
  highlightjsCDN: //cdn.bootcss.com
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  MathJaxCDN: //cdn.bootcss.com
  MathJaxVersion: 2.7.1
  logo:
    image: Color/RStudio-Education.jpg
    width: 220.85
    height: 40
    alt: RStudio Education
  footer:
    github_url: 'https://github.com/rstudio-education'
    twitter_url: 'https://twitter.com/hashtag/rstats'
    copyright: '&copy; [RStudio Inc.](https://www.rstudio.com/), {year}'
    support: 'Proudly supported by '
  authors:
    show_list: ''
    show_single: ''
    show_latest: ''
    label_latest: ''
  events:
    link_archive: ''
  colors:
    text: '#1a1917'
    link: '#1a9a9d'
    link_hover: '#1a9a9d'
    footer_primary: '#767381'
    footer_text: '#e3eef8'
    background: white
    home_section_odd: white
    home_section_even: '#f0eee9'
    menu_primary: '#519199'
    menu_text: '#fff'
    menu_text_active: '#fff'
    menu_text_current: '#519199'
    menu_decorate_current: none
    menu_title: '#fff'
    menu_title_active: '#deef03'
    menu_box_hover: '#7db3ba'
    menu_box_active: white
    header_background: '#dfe3eb'
    table_row_even: '#f7faff'
    table_row_odd: '#fff'
    latest_border: '#dae8f6'
